import Head from 'next/head';
import Login from '../components/Login';

import { useSelector } from 'react-redux';

export default function Home() {
  // glpat-DzNrtE1x7YUxyKTj1Sga

  const data = useSelector((state) => state.user);

  console.log(data);

  return (
    <div>
      <Head>
        <title>Login With Token | Gitlab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Login />
    </div>
  );
}
