import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

import Loader from 'react-loader-spinner';

import { useSelector, useDispatch } from 'react-redux';
import { fetchUser } from '../store/user/userAPI';
import { fetchUserToken } from '../store/user/userSlice';

export default function Home() {
  // glpat-DzNrtE1x7YUxyKTj1Sga

  const data = useSelector((state) => state.user);
  const dispatch = useDispatch();

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Login With Token | Gitlab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {' '}
        <div>
          <input
            type="text"
            placeholder="Enter Your API Token"
            onChange={(e) => {
              dispatch(fetchUserToken(e.target.value));
            }}
          />
          <button
            onClick={() => {
              fetchUser(data.token, dispatch);
            }}
          >
            Get
          </button>
        </div>
        {data.loading ? (
          <Loader
            type="Puff"
            color="#00BFFF"
            height={40}
            width={40}
            timeout={10000}
          />
        ) : data.error ? (
          <p>{data.error}</p>
        ) : (
          <div>
            {/* <Image src={data.users.avatar_url} alt="profile_pic" /> */}
            <h2>{data.users.name}</h2>
            <Link href={'/'}>Project List</Link>
          </div>
        )}
      </main>
    </div>
  );
}
